stages:
- name: Build
  steps:
  - runScriptConfig:
      image: golang:latest
      shellScript: |-
        mkdir -p /go/src/github.com/Liviu2018/rancher
        ln -s `pwd` /go/src/github.com/Liviu2018/rancher/pipeline-example-go
        cd /go/src/github.com/Liviu2018/rancher/pipeline-example-go
        go build -o bin/hello-server
        go test -cover
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: example-helloserver:${CICD_EXECUTION_SEQUENCE}
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
notification: {}

